name: Docker Image CI

on:
  push:
    tags:
      - "*.*.*"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Get current git tag
        id: tag
        uses: devops-actions/action-get-tag@v1.0.1

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag backdevs/box:${{steps.tag.outputs.tag}}
