name: Tag with the latest Box version

on:
  schedule:
    - cron: '22 * * * *'

jobs:
  - name: Get latest Box version
    id: box
    uses: pozetroninc/github-action-get-latest-release@master
    with:
      owner: box-project
      repo: box
      excludes: prerelease, draft
      token: ${{ secrets.GH_PERSONAL_TOKEN }}

  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Tag repository
    id: tag
    uses: mathieudutour/github-tag-action@v6.1
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      custom_tag: ${{ steps.box.outputs.release }}
      tag_prefix: ""

  - name: Create a GitHub release
    uses: ncipollo/release-action@v1
    with:
      tag: ${{ steps.tag.outputs.new_tag }}
      name: Release ${{ steps.tag.outputs.new_tag }}
      body: ${{ steps.box.outputs.description }}